USE UNIVER;
GO

SELECT AT.AUDITORIUM_TYPENAME, A.AUDITORIUM
FROM AUDITORIUM_TYPE AS AT
FULL OUTER JOIN AUDITORIUM AS A ON AT.AUDITORIUM_TYPE = A.AUDITORIUM_TYPE
WHERE A.AUDITORIUM IS NULL; 
GO

SELECT AT.AUDITORIUM_TYPENAME, A.AUDITORIUM
FROM AUDITORIUM_TYPE AS AT
FULL OUTER JOIN AUDITORIUM AS A ON AT.AUDITORIUM_TYPE = A.AUDITORIUM_TYPE
WHERE AT.AUDITORIUM_TYPENAME IS NULL; 
GO

SELECT COUNT(*) AS [Всего несостыковок]
FROM AUDITORIUM_TYPE AS AT
FULL OUTER JOIN AUDITORIUM AS A ON AT.AUDITORIUM_TYPE = A.AUDITORIUM_TYPE
WHERE AT.AUDITORIUM_TYPE IS NULL OR A.AUDITORIUM_TYPE IS NULL;
GO