USE UNIVER;
GO

SELECT 
    F.FACULTY_NAME AS [Факультет], 
    P.PULPIT_NAME AS [Кафедра], 
    PR.PROFESSION_NAME AS [Специальность], 
    S.SUBJECT_NAME AS [Дисциплина], 
    ST.NAME AS [Имя Студента], 
    CASE 
        WHEN PROG.NOTE = 6 THEN N'шесть'
        WHEN PROG.NOTE = 7 THEN N'семь'
        WHEN PROG.NOTE = 8 THEN N'восемь'
    END AS [Оценка]
FROM PROGRESS AS PROG
INNER JOIN STUDENT AS ST ON PROG.IDSTUDENT = ST.IDSTUDENT
INNER JOIN SUBJECT AS S ON PROG.SUBJECT = S.SUBJECT
INNER JOIN PULPIT AS P ON S.PULPIT = P.PULPIT
INNER JOIN GROUPS AS G ON ST.IDGROUP = G.IDGROUP
INNER JOIN PROFESSION AS PR ON G.PROFESSION = PR.PROFESSION
INNER JOIN FACULTY AS F ON PR.FACULTY = F.FACULTY
WHERE PROG.NOTE BETWEEN 6 AND 8
ORDER BY PROG.NOTE DESC;