USE UNIVER;
GO

--UPDATE PROGRESS SET NOTE = 10 
--WHERE IDSTUDENT = 1015 AND SUBJECT = N'СУБД';
--GO

SELECT NAME FROM STUDENT 
WHERE IDSTUDENT IN (
    SELECT IDSTUDENT FROM PROGRESS 
    WHERE NOTE > ALL (SELECT NOTE FROM PROGRESS WHERE SUBJECT = N'КГ')
);