USE UNIVER;
GO

SELECT A1.AUDITORIUM_NAME, A1.AUDITORIUM_CAPACITY, A1.AUDITORIUM_TYPE
FROM AUDITORIUM A1
WHERE A1.AUDITORIUM_CAPACITY = (
    SELECT TOP 1 A2.AUDITORIUM_CAPACITY 
    FROM AUDITORIUM A2
    WHERE A2.AUDITORIUM_TYPE = A1.AUDITORIUM_TYPE
    ORDER BY A2.AUDITORIUM_CAPACITY DESC
);