USE UNIVER;
GO

--INSERT INTO PROGRESS (SUBJECT, IDSTUDENT, PDATE, NOTE) 
--VALUES (N'БД', 1001, GETDATE(), 9);
--GO
SELECT 
    (SELECT AVG(CAST(NOTE AS float)) FROM PROGRESS WHERE SUBJECT = N'ОАиП') AS [Средний ОАиП],
    (SELECT AVG(CAST(NOTE AS float)) FROM PROGRESS WHERE SUBJECT = N'БД') AS [Средний БД],
    (SELECT AVG(CAST(NOTE AS float)) FROM PROGRESS WHERE SUBJECT = N'СУБД') AS [Средний СУБД]
FROM (SELECT TOP 1 * FROM PROGRESS) AS Dummy;