USE UNIVER;
GO

--INSERT INTO FACULTY (FACULTY, FACULTY_NAME) 
--VALUES (N'ФЗО', N'Факультет заочного обучения');
--GO

SELECT F.FACULTY_NAME 
FROM FACULTY F
WHERE NOT EXISTS (
    SELECT * FROM PULPIT P WHERE P.FACULTY = F.FACULTY
);
