USE UNIVER;
GO

SELECT DISTINCT P.PULPIT_NAME
FROM PULPIT P
INNER JOIN FACULTY F ON P.FACULTY = F.FACULTY
INNER JOIN PROFESSION PR ON F.FACULTY = PR.FACULTY
WHERE PR.PROFESSION_NAME LIKE N'%технолог%';